In [11]:
#Create a random tensor with shape (7, 7).
import torch

torch.manual_seed(3)
my_tensor = torch.rand(7,7)
my_tensor

tensor([[0.0043, 0.1056, 0.2858, 0.0270, 0.4716, 0.0601, 0.7719],
        [0.7437, 0.5944, 0.8879, 0.4510, 0.7995, 0.1498, 0.4015],
        [0.0542, 0.4594, 0.1756, 0.9492, 0.8473, 0.8749, 0.6483],
        [0.2148, 0.9493, 0.0121, 0.1809, 0.1877, 0.2927, 0.5997],
        [0.1213, 0.1148, 0.2609, 0.8052, 0.1394, 0.0516, 0.0666],
        [0.2540, 0.3686, 0.0043, 0.2659, 0.5096, 0.5824, 0.4283],
        [0.4433, 0.1747, 0.7562, 0.3795, 0.1581, 0.3796, 0.4301]])

In [12]:
#Perform a matrix multiplication on the tensor from 2 with another 
#random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).
#Set the random seed to 0 and do 2 & 3 over again.
torch.manual_seed(3)
tensor2 = torch.rand(1,7)
torch.matmul(my_tensor, tensor2.T)

tensor([[0.9154],
        [1.0278],
        [1.0771],
        [0.6785],
        [0.2292],
        [0.6544],
        [0.6761]])

In [23]:
#Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? 
#(hint: you'll need to look into the documentation for torch.cuda for this one)
torch.cuda.manual_seed(1234)
gpu_tensor = torch.rand((7,7),device='cuda')
gpu_tensor

tensor([[0.1272, 0.8167, 0.5440, 0.6601, 0.2721, 0.9737, 0.3903],
        [0.3394, 0.5451, 0.7312, 0.3864, 0.5959, 0.7578, 0.2126],
        [0.7198, 0.9845, 0.5518, 0.0981, 0.0582, 0.5839, 0.1083],
        [0.9461, 0.3170, 0.8328, 0.6676, 0.2886, 0.9022, 0.8115],
        [0.1784, 0.9534, 0.1486, 0.3882, 0.7977, 0.1752, 0.5777],
        [0.1949, 0.8499, 0.3125, 0.2156, 0.0383, 0.4934, 0.3138],
        [0.3121, 0.5664, 0.1266, 0.7097, 0.0040, 0.5147, 0.2811]],
       device='cuda:0')

In [28]:
#Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this).
#Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed).
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}")
torch.manual_seed(1234)
tensor1 = torch.rand(2,3)
tensor2 = torch.rand(2,3)
gpu_tensor1 = tensor1.to(device)
gpu_tensor2 = tensor2.to(device)
gpu_tensor1, gpu_tensor2

Device: cuda


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))

In [34]:
#Perform a matrix multiplication on the tensors you created in 28 (again, 
#you may have to adjust the shapes of one of the tensors).
mult_res = torch.matmul(gpu_tensor1, gpu_tensor2.T)
mult_res, mult_res.size()

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'),
 torch.Size([2, 2]))

In [39]:
#Find the maximum and minimum values of the output of 34.
mult_max = mult_res.max()
print(f"max: {mult_max}")
mult_min = mult_res.min()
print(f"min: {mult_min}")

max: 0.5617256760597229
min: 0.3647301495075226


In [40]:
#Find the maximum and minimum index values of the output of 7.
mult_max_pos = mult_res.argmax()
print(f"max position: {mult_max_pos}")
mult_min_pos = mult_res.argmin()
print(f"min position: {mult_min_pos}")

max position: 3
min position: 0


In [54]:
#Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all
#the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when
#you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.
torch.manual_seed(7)
x = torch.randn(1, 1, 1, 10)
new_x = x.squeeze()
print(f"x: {x}, shape: {x.shape}")
print(f"new_x: {new_x}, shape: {new_x.shape}")

x: tensor([[[[-0.1468,  0.7861,  0.9468, -1.1143,  1.6908, -0.8948, -0.3556,
            1.2324,  0.1382, -1.6822]]]]), shape: torch.Size([1, 1, 1, 10])
new_x: tensor([-0.1468,  0.7861,  0.9468, -1.1143,  1.6908, -0.8948, -0.3556,  1.2324,
         0.1382, -1.6822]), shape: torch.Size([10])


In [50]:
reshaped = x.view(5,3)
reshaped

tensor([[ 0.4501,  0.2709, -0.8087],
        [-0.0217, -1.0413,  0.0702],
        [ 0.5797, -0.0599,  0.1816],
        [-0.6797, -0.2567, -1.8189],
        [ 0.2111,  0.3372,  0.6638]])